# Generated by Django 4.2.5 on 2023-11-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('envio_solicitud', 'Usuario ha enviado una solicitud'), ('aprobacion', 'Tu solicitud fue aprobada'), ('rechazo', 'Tu solicitud fue rechazada')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
