# Generated by Django 4.2.5 on 2023-11-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_notificaciones', to='core.customuser'),
        ),
    ]
